apiVersion: v1
kind: ReplicationController
metadata:
  name: greenreplicationcontroller
  labels:
    app: green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - image: "mreddy7/capstonegreen"
        name: green
        ports:
          - containerPort: 80
            name: http